services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_spring
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
    secrets:
      - mongo_root_username
      - mongo_root_password
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backend:
    build: .
    container_name: spring_backend
    ports:
      - "9091:9090"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/back_end?authSource=admin
      - ACCESS_TOKEN_SECRET_FILE=/run/secrets/access_token_secret
      - REFRESH_TOKEN_SECRET_FILE=/run/secrets/refresh_token_secret
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/actuator/health/liveness"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    secrets:
      - access_token_secret
      - refresh_token_secret

networks:
  spring-network:
    driver: bridge
    internal: true  # Prevents external access to the network

volumes:
  mongodb_data:
    name: spring_mongodb_data

secrets:
  mongo_root_username:
    file: ./secrets/mongo_root_username.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  access_token_secret:
    file: ./secrets/access_token_secret.txt
  refresh_token_secret:
    file: ./secrets/refresh_token_secret.txt