services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_spring
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring_backend
    ports:
      - "9091:9090"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/back_end
      - ACCESS_TOKEN_SECRET=test
      - REFRESH_TOKEN_SECRET=test
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-network:
    driver: bridge

volumes:
  mongodb_data:
    name: spring_mongodb_data