services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_spring
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spring-network

  backend:
    build: .
    container_name: spring_backend
    ports:
      - "9091:9090"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb_spring:27017/back_end
      - ACCESS_TOKEN_SECRET=test
      - REFRESH_TOKEN_SECRET=test
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  mongodb_data:
    name: spring_mongodb_data