apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: grafana-auth
type: Opaque
data:
  admin-user: YWRtaW4=      # "admin" en base64
  admin-password: c3Ryb25ncGFzc3dvcmQ=  # "strongpassword" en base64