# spring-deployment.yaml (version complète)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: monitoring
  labels:
    app: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8086"
    spec:
      # spring-deployment.yaml
      containers:
        - name: spring-backend
          image: narjesknaz/spring-backend:165
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 8086
              name: metrics
          livenessProbe: # Corriger l'indentation ici
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe: # Corriger l'indentation ici
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: backend-configmap
          env:
            - name: MANAGEMENT_SERVER_PORT
              value: "8086"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT
              value: "true"
            - name: MANAGEMENT_ENDPOINT_METRICS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_ENABLE_ALL
              value: "true"
