apiVersion: v1
kind: Service
metadata:
  name: spring-backend
  namespace: monitoring
  labels:
    app: spring-backend
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: http
    - port: 8086
      targetPort: 8086
      name: metrics
  selector:
    app: spring-backend