apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-prometheus-prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30091  # Changé de 30090 à 30091
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: monitoring-kube-prometheus-prometheus