apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: monitoring
  labels:
    app: spring-backend
spec:
  selector:
    matchLabels:
      app: spring-backend
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      targetPort: 8085
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s