apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: monitoring
  labels:
    app: spring-backend
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: spring-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 14s
      scheme: http
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'jvm_.*|process_.*|http_.*|spring_.*|tomcat_.*|system_.*'
          action: keep