apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: monitoring
  labels:
    app: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: spring-backend
          image: narjesknaz/spring-backend:165
          ports:
            - containerPort: 9090
              name: http
          envFrom:
            - configMapRef:
                name: backend-configmap
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 130
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT
              value: "true"
            - name: SPRING_SECURITY_ENABLED
              value: "false"
            - name: MANAGEMENT_ENDPOINT_METRICS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_ENABLE_ALL
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_AUTHENTICATION_ENABLED
              value: "false"