apiVersion: v1
kind: Service
metadata:
  name: spring-backend
  namespace: monitoring
  labels:
    app: spring-backend
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  selector:
    app: spring-backend