prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true
    serviceMonitorSelector:
      matchLabels:
        app: spring-backend
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    storageSpec: null

  server:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    service:
      type: NodePort
      nodePort: 30090
      targetPort: 9090
      port: 9090

  persistentVolume:
    enabled: false

  alertmanager:
    enabled: true
    persistentVolume:
      enabled: false
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
        routes:
          - match:
              alertname: Watchdog
            receiver: 'null'
      receivers:
        - name: 'null'

  nodeExporter:
    enabled: false

  kubeStateMetrics:
    enabled: true