# spring-boot-app/charts/mongodb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{- toYaml .Values.mongodb.secrets | nindent 2 }}