# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: pronto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: narjesknaz/spring-backend:latest
          imagePullPolicy: Always
          envFrom:                      # Ajout des variables d'environnement
            - configMapRef:
                name: backend-configmap
      imagePullSecrets:
        - name: regcred