apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  selector:
    matchLabels:
      app: spring-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: narjesknaz/spring-backend:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/back_end"
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: access-token-secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: refresh-token-secret
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 15  # Add this to give more time for initial startup

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60  # Increase this
            periodSeconds: 10
            failureThreshold: 5     # Add this to be more lenient