apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  # or NodePort depending on your needs
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9090