apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  template:
    spec:
      containers:
        - name: spring-backend
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness  # Changed from /actuator/health
              port: 9090
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness  # Changed from /actuator/health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3