# mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # You should change these values using: echo -n "your-value" | base64
  MONGODB_ROOT_PASSWORD: bW9uZ28tcGFzcw== # mongo-pass
  MONGODB_PASSWORD: bW9uZ28tcGFzcw==      # mongo-pass