apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: back_end-backend  # Assurez-vous que l'image existe et est correctement taguée
          ports:
            - containerPort: 9090  # Port exposé dans le container
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb-service:27017/back_end  # Connexion à MongoDB
            - name: ACCESS_TOKEN_SECRET
              value: test  # Secret pour le token d'accès
            - name: REFRESH_TOKEN_SECRET
              value: test  # Secret pour le token de rafraîchissement
