# Spring Boot Backend Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: spring-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb-service:27017/back_end"
            - name: ACCESS_TOKEN_SECRET
              value: "test"
            - name: REFRESH_TOKEN_SECRET
              value: "test"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  type: NodePort
  selector:
    app: spring-backend
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090