# spring-boot-app/templates/backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{- toYaml .Values.backend.secrets | nindent 2 }}